jobobby04/TachiyomiSY

app/src/main/java/eu/kanade/tachiyomi/ui/browse/source/browse/BrowseSourceController.kt, app/src/main/java/eu/kanade/tachiyomi/ui/browse/source/browse/BrowseSourcePresenter.kt, app/src/main/java/eu/kanade/tachiyomi/ui/browse/source/browse/RecommendsPager.kt, app/src/main/java/eu/kanade/tachiyomi/ui/manga/MangaAllInOneController.kt, app/src/main/java/eu/kanade/tachiyomi/ui/manga/info/MangaInfoController.kt
=> Smart recommendations

app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferenceKeys.kt, app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferencesHelper.kt, app/src/main/java/eu/kanade/tachiyomi/ui/library/LibraryPresenter.kt, app/src/main/java/eu/kanade/tachiyomi/ui/library/LibrarySettingsSheet.kt, app/src/main/res/values/strings_extra.xml
=> Implement lewd filter

README.md
=> Fixed a spelling error

app/src/main/java/eu/kanade/tachiyomi/source/online/all/Hitomi.kt
Tested on the extension I'm making, should work for you.
=> Fix Hitomi chapters

app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferenceValues.kt, app/src/main/java/eu/kanade/tachiyomi/ui/base/activity/BaseActivity.kt, app/src/main/java/eu/kanade/tachiyomi/ui/setting/SettingsGeneralController.kt, app/src/main/res/values/colors.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/styles.xml, app/src/main/res/values/themes.xml
=> Cool gray theme 

app/src/main/java/exh/recs/RecommendsPager.kt
=> Use a different title for japanese manga vs other manga

app/src/main/java/eu/kanade/tachiyomi/ui/reader/ReaderActivity.kt, app/src/main/java/eu/kanade/tachiyomi/ui/reader/chapter/ReaderChapterSheet.kt, app/src/main/res/drawable/chapter_nav.xml, app/src/main/res/drawable/ic_merge_type_24dp.xml, app/src/main/res/drawable/reader_menu_bottom.xml, app/src/main/res/drawable/readernav_rounded.xml, app/src/main/res/layout/manga_info_header.xml, app/src/main/res/layout/reader_activity.xml, app/src/main/res/menu/reader.xml, app/src/main/res/values/colors.xml
- New reader UI
- Adjustments to Midnight Dusk accent colour to make soi happy
- Updated merge icon
- And idk i think that's about it
=> Reader PR + stuff

app/src/main/res/layout/reader_activity.xml
webview vs filter in the reader. 
put webview which rarely(compared to filter, i think) being used in the reader on the left and put filter clloser to hand
<table>
<tr>
<td>before
<td>after
<tr>
<td><img src="https://cdn.discordapp.com/attachments/745641917269671966/818430804610383902/Screenshot_2021-03-08-17-31-31-008_eu.kanade.tachiyomi.sy.jpg">
<td><img src="https://cdn.discordapp.com/attachments/745641917269671966/818429592087035944/1615199197154.jpg"
</table>
=> swap webview and filter

app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferenceValues.kt, app/src/main/java/eu/kanade/tachiyomi/ui/base/activity/BaseThemedActivity.kt, app/src/main/java/eu/kanade/tachiyomi/ui/setting/SettingsGeneralController.kt, app/src/main/res/values/colors.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/strings_sy.xml, app/src/main/res/values/styles.xml, app/src/main/res/values/themes_sy.xml
_tired of the blue accent color of the amoled theme? wait no more_
=> Added "Hot Pink" theme

app/src/main/res/values/colors.xml, app/src/main/res/values/themes_sy.xml
=> Tweak "Hot Pink" theme

app/src/main/java/eu/kanade/tachiyomi/ui/category/repos/RepoPresenter.kt, app/src/main/res/values/strings_sy.xml
Updated the Regex to support Repository and usernames with numbers in them.
=> add support for Repos with Numbers in their name

app/src/main/java/eu/kanade/tachiyomi/ui/setting/SettingsBackupController.kt
Fixes crash when trying to send backup to Tachidesk
=> Tachidesk backup

app/src/main/res/values/themes_sy.xml
only in midnight dusk and hot pink theme
new nav bar scrim already make it semi transparent
Closes #290
=> fix invisible system nav bar

app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferenceKeys.kt, app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferencesHelper.kt, app/src/main/java/eu/kanade/tachiyomi/source/online/all/MangaDex.kt, app/src/main/java/eu/kanade/tachiyomi/ui/main/MainActivity.kt, app/src/main/java/eu/kanade/tachiyomi/ui/more/MoreController.kt, app/src/main/java/eu/kanade/tachiyomi/ui/setting/SettingsGeneralController.kt, app/src/main/res/values/strings.xml
Add an option to hide update and history buttons in nivagation bar
=> hide update and history buttons option

app/src/main/res/values/colors.xml, app/src/main/res/values/themes.xml, app/src/main/res/values/themes_sy.xml
=> Fix SY themes after custom ripple changes

app/src/main/res/values-ru/strings_sy.xml
Clean version https://github.com/jobobby04/TachiyomiSY/pull/292 after https://github.com/tachiyomiorg/tachiyomi/pull/4996 .
This time merge it without waiting for the release.
=> Rus locale fix/additions

app/src/main/java/eu/kanade/tachiyomi/ui/main/MainActivity.kt
the long awaited fix finally released
=> Fix label visibility for tablet ui

app/src/main/res/values/themes_sy.xml
=> Fix black/invisible nav in AmoledBlue theme

app/src/main/res/values-ru/strings_sy.xml, app/src/main/res/values/strings_sy.xml
=> Rus new strings (+fix original)

app/src/main/res/values-pt-rBR/strings_sy.xml
fix grammar and reduce some strings to fit in some fields
=> tweak the PT-BR translation

app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferenceKeys.kt, app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferencesHelper.kt, app/src/main/java/eu/kanade/tachiyomi/ui/browse/migration/advanced/design/MigrationBottomSheetDialog.kt, app/src/main/java/eu/kanade/tachiyomi/ui/browse/migration/advanced/process/MigrationListController.kt, app/src/main/java/eu/kanade/tachiyomi/ui/browse/migration/advanced/process/MigrationProcessAdapter.kt, app/src/main/java/eu/kanade/tachiyomi/ui/browse/migration/advanced/process/MigrationProcessHolder.kt, app/src/main/res/layout/migration_bottom_sheet.xml, app/src/main/res/values/strings_sy.xml
- Added margin top for FAB in migration_bottom_sheet.xml looks slightly better now
- Implement feature for hiding not found manga in mass migration. Migrating a large amount of manga and checking if the migration is correct is more difficult if you have to flip through a manga that was not found
Need some testing\review
=> Add Migrate button marginTop and implement Hide not found manga for mass migration

app/src/main/java/eu/kanade/tachiyomi/ui/browse/migration/advanced/process/MigrationListController.kt, app/src/main/res/layout/reader_activity.xml
fix previous button color in vertical seekbar
fix migration button color
=> fix toolbar btn color 

app/src/main/java/eu/kanade/tachiyomi/data/backup/full/models/BackupManga.kt
See: https://github.com/Jays2Kings/tachiyomiJ2K/issues/878 and https://github.com/Jays2Kings/tachiyomiJ2K/commit/2dc61cb070ec7451ee31844326c93bd65f6ef6d4#diff-2eb34be6bfde24e16a10af091a0cc7cfe3fd724e68e59bd74a2a9cebc54a601c
=> Sync J2K fields in BackupManga to fix duplicate protobuf ID

app/src/main/java/eu/kanade/tachiyomi/ui/setting/SettingsAppearanceController.kt, app/src/main/res/values/strings_sy.xml
changes made entirely in GitHub browser :crossed_fingers:
=> Create Navbar category in Appearance settings

app/src/main/java/eu/kanade/tachiyomi/ui/manga/info/MangaInfoHeaderAdapter.kt, app/src/main/res/drawable/ic_status_cancelled_24dp.xml, app/src/main/res/drawable/ic_status_hiatus_24dp.xml, app/src/main/res/drawable/ic_status_publication_complete_24dp.xml
Psss Psss Pss 🐱 
| Cancelled | Publication Complete | Hiatus |
| ------- | ------- | ------- |
| ![image](https://user-images.githubusercontent.com/10836780/132062479-c5d6295b-5299-456f-bc51-e0f6326dcfeb.png) | ![image](https://user-images.githubusercontent.com/10836780/132062506-de38c15f-545e-4504-9726-feed0914af76.png) | ![image](https://user-images.githubusercontent.com/10836780/132062655-ba240cb0-b77f-41ff-93bd-ee22c3a477cd.png) |
=> Add SY-specific status icons

app/src/main/res/values-in/strings_sy.xml
Add Indonesian translation for many SY strings
=> Add Indonesian translation for SY strings

app/src/main/java/exh/ui/batchadd/BatchAddController.kt, app/src/main/res/layout/eh_fragment_batch_add.xml
=> BatchAdd fixes

app/src/main/java/eu/kanade/tachiyomi/ui/manga/EditMangaDialog.kt, app/src/main/res/layout/edit_manga_dialog.xml
=> EditManga fixes

app/src/main/res/layout/migration_bottom_sheet.xml, app/src/main/res/layout/migration_manga_card.xml, app/src/main/res/layout/migration_process_item.xml
=> Migration fixes

app/src/main/res/layout/reader_activity.xml
=> Fixing few things in ReaderActivity.xml

app/src/main/res/values-ru/strings_sy.xml
=> Russian translation

app/src/main/java/eu/kanade/tachiyomi/source/online/all/MangaDex.kt, app/src/main/java/exh/md/handlers/AzukiHandler.kt, app/src/main/java/exh/md/handlers/MangaHotHandler.kt, app/src/main/java/exh/md/handlers/PageHandler.kt
Azuki Manga using watermarked version of images as the regular versions have DRM.
=> Add support for Azuki Manga and MangaHot Chapters in Mangadex

app/src/main/java/exh/util/MangaType.kt
That's all for now, will add more later
=> Adding new sites for auto reading mode trigger

app/src/main/java/eu/kanade/tachiyomi/ui/reader/ReaderPresenter.kt
=> Check "Save pages into separate folder" setting when saving Combined images as well

app/src/main/java/eu/kanade/tachiyomi/ui/browse/migration/advanced/design/MigrationBottomSheetDialog.kt, app/src/main/res/layout/migration_bottom_sheet.xml
=> Tweaks to migration sheet

app/src/main/res/values-zh-rCN/strings_sy.xml
Found some translation errors
Need more feedback
=> [zh_rCN] Translation Correction

app/src/main/java/exh/util/LewdMangaChecker.kt
add Multporn, VCPVMP to lewd filter
=> filter 3 more sources

app/src/main/java/exh/md/dto/StatisticsDto.kt, app/src/main/java/exh/md/handlers/ApiMangaParser.kt
Refer: https://github.com/CarlosEsco/Neko/pull/1001
=> Use Bayesian Rating for Manga info

app/src/main/res/values-ru/strings_sy.xml
=> [RU] Translations

app/src/main/java/eu/kanade/presentation/manga/MangaScreen.kt, app/src/main/java/eu/kanade/presentation/manga/components/MangaAppBar.kt, app/src/main/java/eu/kanade/presentation/manga/components/MangaInfoHeader.kt, app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferencesHelper.kt, app/src/main/java/eu/kanade/tachiyomi/ui/manga/MangaPresenter.kt, app/src/main/java/eu/kanade/tachiyomi/ui/setting/SettingsGeneralController.kt, app/src/main/res/values/strings_sy.xml
Resolves https://github.com/jobobby04/TachiyomiSY/issues/553, supersedes https://github.com/jobobby04/TachiyomiSY/pull/653.
=> Able to move 'Merge' button to overflow menu

app/src/main/java/eu/kanade/tachiyomi/ui/reader/ReaderActivity.kt
Fixes https://github.com/jobobby04/TachiyomiSY/issues/551
=> Fixes the slider when in 2 page mode

i18n/src/main/res/values-ru/strings_sy.xml, i18n/src/main/res/values/strings_sy.xml
=> Fixes and Translations

i18n/src/main/res/values-ru/strings_sy.xml, i18n/src/main/res/values/strings_sy.xml
=> [RU] Translations and fixes

app/src/main/java/eu/kanade/presentation/more/settings/screen/SettingsReaderScreen.kt
=> Seekbar fixes

app/src/main/java/exh/ui/batchadd/BatchAddController.kt
=> Change delay() time

app/src/main/java/eu/kanade/presentation/browse/components/BrowseSourceEHentaiList.kt, app/src/main/java/eu/kanade/presentation/browse/components/MigrationActionIcon.kt, app/src/main/java/eu/kanade/presentation/browse/components/MigrationMangaDialog.kt, app/src/main/java/eu/kanade/presentation/more/settings/screen/SettingsBackupScreen.kt, app/src/main/java/eu/kanade/tachiyomi/ui/browse/migration/advanced/process/MigrationListScreen.kt, app/src/main/java/eu/kanade/tachiyomi/ui/library/LibraryScreen.kt, app/src/main/java/eu/kanade/tachiyomi/ui/manga/MangaScreen.kt, app/src/main/java/eu/kanade/tachiyomi/ui/manga/MangaScreenModel.kt, app/src/main/java/eu/kanade/tachiyomi/ui/manga/merged/EditMergedSettingsDialog.kt, app/src/main/java/exh/GalleryAdder.kt, app/src/main/java/exh/favorites/FavoritesSyncHelper.kt, app/src/main/java/exh/ui/intercept/InterceptActivity.kt, app/src/main/java/exh/ui/metadata/adapters/MetadataUIUtil.kt, app/src/main/java/exh/ui/smartsearch/SmartSearchScreen.kt, app/src/main/java/exh/util/MangaType.kt, app/src/main/res/layout/edit_merged_settings_header.xml, app/src/main/res/layout/migration_bottom_sheet.xml, app/src/main/res/values/arrays_sy.xml, i18n/src/main/res/values-fr/strings_sy.xml, i18n/src/main/res/values-in/strings_sy.xml, i18n/src/main/res/values-pt-rBR/strings_sy.xml, i18n/src/main/res/values-ru/strings_sy.xml, i18n/src/main/res/values-zh-rCN/strings_sy.xml, i18n/src/main/res/values/strings_sy.xml
=> Translations

app/src/main/java/eu/kanade/tachiyomi/ui/reader/ReaderActivity.kt, app/src/main/java/eu/kanade/tachiyomi/ui/reader/ReaderViewModel.kt, app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/pager/Pager.kt, app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/pager/PagerViewer.kt
I finally made it. I have no idea how you do your commented fork changes, I just take the conflicts as I see them 😅
[doublepage-orientation-change.webm](https://user-images.githubusercontent.com/8617760/218923509-24274415-0be4-4720-9ae1-7591acdb0c60.webm)
=> Fix double page progress when changing orientation

app/src/main/java/eu/kanade/domain/source/service/SourcePreferences.kt, app/src/main/java/eu/kanade/presentation/more/settings/screen/SettingsAdvancedScreen.kt, app/src/main/java/eu/kanade/tachiyomi/ui/browse/source/SourcesScreenModel.kt, app/src/main/java/eu/kanade/tachiyomi/ui/browse/source/SourcesTab.kt, app/src/main/java/exh/util/DataSaver.kt, i18n/src/main/res/values/strings_sy.xml
Well.. Since Heroku stopped their free service.... Let's add wsrv.nl
=> Use wsrv.nl service

app/src/main/java/exh/smartsearch/SmartSearchEngine.kt
small changes to filtering cryllic letters in SmartSearchEngine
=> fix to cryllic letter filtering

app/src/main/java/eu/kanade/tachiyomi/AppModule.kt
Fixed databases getting overwritten on SQL-Schema update 
thanks for the fix @jobobby04
=> fixed encrypted sql database gets overwritten on sql-schema change

i18n/src/main/res/values-zh-rTW/strings_sy.xml
chinese translation updates fork(zh-rCN)
=> Add Chinese translation

i18n-sy/src/commonMain/resources/MR/zh-rTW/plurals.xml, i18n-sy/src/commonMain/resources/MR/zh-rTW/strings.xml
Changed Simplified Chinese to Traditional Chinese.
=> Update zh-rTW translation

i18n-sy/src/commonMain/resources/MR/zh-rTW/strings.xml
=> Update zh-tw strings.xml

i18n-sy/src/commonMain/resources/MR/base/strings.xml, i18n-sy/src/commonMain/resources/MR/zh-rCN/strings.xml
Translation mistakes correction and missing translation additions
=> zh-rCN translation updates

i18n-sy/src/commonMain/resources/MR/zh-rTW/strings.xml
=> zh-tw Update strings.xml

app/src/main/java/eu/kanade/tachiyomi/ui/manga/EditMangaDialog.kt
| Before | After |
| ![](https://media.discordapp.net/attachments/825346400953827349/1203246942755233832/image.png) | ![](https://media.discordapp.net/attachments/825346400953827349/1203238367039328267/image.png) |
=> Fix blank textbox if null

app/src/main/java/eu/kanade/domain/track/interactor/TrackChapter.kt, app/src/main/java/eu/kanade/tachiyomi/data/library/LibraryUpdateJob.kt, app/src/main/java/eu/kanade/tachiyomi/data/track/TrackStatus.kt, app/src/main/java/eu/kanade/tachiyomi/data/track/mdlist/MdList.kt, app/src/main/java/eu/kanade/tachiyomi/ui/manga/MangaScreenModel.kt, app/src/main/java/exh/md/handlers/FollowsHandler.kt, app/src/main/java/exh/md/utils/FollowStatus.kt
Change from: `enum class FollowStatus(val int: Long)`
To: `enum class FollowStatus(val long: Long)`
=> Rename MangaDex's FollowStatus's property to better reflect its type

core/common/src/main/kotlin/eu/kanade/tachiyomi/util/storage/CbzCrypto.kt
Passwords will no longer be converted to strings and the arrays that contain them will be overwritten were applicable.
see [here](https://www.baeldung.com/java-storing-passwords) for more information.
=> Safer password handling

app/src/main/java/eu/kanade/tachiyomi/data/backup/restore/restorers/CategoriesRestorer.kt
Also see:
- https://github.com/mihonapp/mihon/pull/635
- https://github.com/mihonapp/mihon/issues/632
=> fix: check order before restore from backup

README.md
Changed DO and DON'T for bug repports to a link with the issue template.
Closes https://github.com/jobobby04/TachiyomiSY/issues/1173
=> README.md patch links #1173

i18n-sy/src/commonMain/resources/MR/fr/strings.xml, i18n-sy/src/commonMain/resources/MR/in/strings.xml, i18n-sy/src/commonMain/resources/MR/pt-rBR/strings.xml, i18n-sy/src/commonMain/resources/MR/zh-rTW/strings.xml
remove non-default string resources
=> Fix build warning

app/src/main/java/eu/kanade/tachiyomi/source/online/all/MangaDex.kt, app/src/main/java/exh/md/handlers/NamicomiHandler.kt, app/src/main/java/exh/md/handlers/PageHandler.kt
This PR adds a Namicomi page handler for MD.
It also implements data saver support for that external source.
=> Add Namicomi support for external chapters on MD

i18n-sy/src/commonMain/resources/MR/zh-rTW/strings.xml
=> Update TW strings.xml

app/src/main/java/eu/kanade/domain/sync/SyncPreferences.kt, app/src/main/java/eu/kanade/tachiyomi/data/sync/service/GoogleDriveSyncService.kt
Improve google drive sync, removes the lock, change to protobuf, and potentially fix deviceId not being unique, since it wasn't an appState (Existing users probably need a reinstall so it generates a new unique app id, if they have checked sync app settings)
Maybe:
fixes #1171 
fixes #1168
=> chore: improve google drive sync.

app/src/main/java/eu/kanade/tachiyomi/ui/reader/ReaderViewModel.kt
=> Delete duplicate downloaded chapters when they are automatically marked as read.

app/src/main/java/eu/kanade/tachiyomi/source/online/all/MangaDex.kt, app/src/main/java/exh/md/dto/MangaDto.kt, app/src/main/java/exh/md/handlers/ApiMangaParser.kt, app/src/main/java/exh/md/handlers/MangaHandler.kt, app/src/main/java/exh/md/service/MangaDexService.kt, app/src/main/java/exh/md/utils/MdApi.kt
For delegated MangaDex.
Closes #1097
=> Respect `thumbnailQuality` and `tryUsingFirstVolumeCover` preference.

app/src/main/java/eu/kanade/presentation/manga/MangaScreen.kt, app/src/main/java/eu/kanade/tachiyomi/ui/manga/MangaScreenModel.kt
=> Show local chapters as downloaded on merged entries.

app/src/main/java/eu/kanade/tachiyomi/source/online/all/MergedSource.kt
Might accidentally removed during implementing mihonapp/mihon#1125
=> honor downloadChapters for merged entries while downloading chapters

app/src/main/java/eu/kanade/tachiyomi/source/online/all/MangaDex.kt, app/src/main/java/exh/md/handlers/ApiMangaParser.kt, app/src/main/java/exh/md/handlers/MangaHandler.kt, app/src/main/java/exh/md/utils/MdUtil.kt, i18n-sy/src/commonMain/moko-resources/base/strings.xml
=> Respect the `altTitlesInDesc` preference (MD)

app/src/main/java/eu/kanade/tachiyomi/data/library/LibraryUpdateJob.kt, app/src/main/java/eu/kanade/tachiyomi/ui/reader/ReaderViewModel.kt
=> allow chapter 0 dupe auto mark as read

app/src/main/java/eu/kanade/presentation/more/settings/screen/SettingsDataScreen.kt, app/src/main/java/eu/kanade/tachiyomi/data/sync/SyncDataJob.kt, app/src/main/java/eu/kanade/tachiyomi/ui/library/LibraryTab.kt
Everything else that triggers a sync except manual "Sync now" presses are counted as automatic.
=> Do not sync automatically when not connected to a network

app/src/main/AndroidManifest.xml, app/src/main/java/eu/kanade/tachiyomi/source/online/english/Pururin.kt, source-api/src/commonMain/kotlin/exh/metadata/metadata/PururinSearchMetadata.kt
Pururin have changed domain to a .me
I have updated domain in the app.
=> Update base URL and host for Pururin to pururin.me
