jobobby04/TachiyomiSY

app/src/main/res/values/themes.xml
md_color_title doesn't seem to be used anywhere except for the manga titles according to my search on ApkEditor (you know, because forks can't be searched😔), and original repo doesn't even seem to be using it for anything - so there shouldn't be unintended consequences.
=> Fix title on light theme

app/src/main/java/eu/kanade/tachiyomi/ui/setting/SettingsMangaDexController.kt, app/src/main/res/values/strings_sy.xml
This PR makes changes in displaying Similar Manga Settings
There are two changes made:
1. Remove redundant R.string.similar_screen text from the settings
2. Replace the "Credits" string with a new appropriate element in strings_sy.xml, aiding complete translation
| before | after |
| --- | --- |
| ![Screenshot_2021-02-26-01-04-42-093_eu kanade tachiyomi sy](https://user-images.githubusercontent.com/72807749/109207159-cf4f9680-77ce-11eb-844b-b86a8e5e0ef7.jpg) | ![Screenshot_2021-02-26-00-59-50-027_eu kanade tachiyomi sy debug](https://user-images.githubusercontent.com/72807749/109206702-34ef5300-77ce-11eb-9b45-488947ab3f0e.jpg) |
=> Change Similar manga settings layout

app/src/main/java/eu/kanade/tachiyomi/ui/setting/SettingsReaderController.kt
This PR changes the way the Reader settings are displayed. The
fork specific settings for the reader have been moved to the bottom
instead of being sandwiched between settings from the main app.
Makes it look a better organised now
`git` tries to minimise deltas so the `git diff` might look a bit strange 
anyways, here's a Video preview of new Reader Settings (with 
Fork settings at the bottom):
https://user-images.githubusercontent.com/72807749/109381260-471cde80-78ff-11eb-87d8-e9d8b4a562a3.mp4
=> Change Reader settings layout

app/src/main/res/layout/migration_manga_card.xml, app/src/main/res/layout/migration_process_item.xml
Do test them out locally before merging the PR
fix Migration process item option button color
fixes #287 
fix migration manga card layout for white theme
=> fixes to Migration menu layouts

README.md, app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferencesHelper.kt, app/src/main/java/eu/kanade/tachiyomi/ui/reader/ReaderPresenter.kt, app/src/main/java/eu/kanade/tachiyomi/ui/reader/setting/ReaderReadingModeSettings.kt, app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/pager/PagerConfig.kt, app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/pager/PagerPageHolder.kt, app/src/main/java/eu/kanade/tachiyomi/ui/setting/SettingsReaderController.kt, app/src/main/java/eu/kanade/tachiyomi/util/system/ImageUtil.kt, app/src/main/res/layout/reader_pager_settings.xml, app/src/main/res/values/arrays_sy.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/strings_sy.xml
Basic implementation of center margins for #628.
This adds a dropdown selector to the bottom of reader preferences when in dual-page mode which allows the user to specify if they want margins inserted between double-page spreads, in the center of large images, both, or neither. The margin is currently fixed at 96px wide as that seems to be the standard size for 'display features' (aka don't-render-here deadspace) according to the android foldables guidelines.
=> Center padding option for Surface Duos/other foldables

app/src/main/java/eu/kanade/tachiyomi/ui/reader/ReaderActivity.kt
Reverts the 2-page slider changes in jobobby04/TachiyomiSY#657 as it's causing crashes. Main issue is needing to consider horizontal/long pages, which displays as 1 page even in 2-page mode (as expected, but makes changing slider behaviour tricky).
Supersedes https://github.com/jobobby04/TachiyomiSY/pull/665
=> Revert "Fixes the slider when in 2 page mode"

gradle/sy.versions.toml
The old version of firebase depends on the library of the closed JCenter, which makes it unable to compile
=> Upgrade Firebase

app/src/main/java/eu/kanade/tachiyomi/data/updater/GithubRelease.kt
TachiyomiSY's (Preview Builds) APKs didn't have this suffix.
The code now causes the corresponding architecture impossible to find, which leads to downloading the APK for arm64 when updating from x86_64.
=> Remove suffix

gradle/kotlinx.versions.toml
fixes #834
Use the newest Version of xmlutil.
This will fix half of the Surrogate pair bug, but even in the newest version Characters between 0xE000 and 0xFFFD will be replaced with NULL characters so disabling the creation of ComicInfo files until the next release of xmlutil, were this new bug will be fixed may be advisable.
More Info on the new Bug here: https://github.com/tachiyomiorg/tachiyomi/issues/9284
=> Bump xmlutil

app/src/main/java/eu/kanade/tachiyomi/ui/reader/loader/ZipPageLoader.kt
`.filterNot` and `!it.isDirectory` were canceling each other out
=> fix ZipPageLoader not working for encrypted cbz archives

app/src/main/java/eu/kanade/presentation/more/settings/screen/SettingsSecurityScreen.kt, app/src/main/java/eu/kanade/tachiyomi/AppModule.kt, app/src/main/java/eu/kanade/tachiyomi/data/coil/TachiyomiImageDecoder.kt, core/src/main/java/eu/kanade/tachiyomi/core/security/SecurityPreferences.kt, core/src/main/java/eu/kanade/tachiyomi/util/storage/CbzCrypto.kt, core/src/main/java/tachiyomi/core/util/system/ImageUtil.kt, i18n/src/main/res/values/strings_sy.xml, source-local/src/androidMain/kotlin/tachiyomi/source/local/LocalSource.kt, source-local/src/androidMain/kotlin/tachiyomi/source/local/image/LocalCoverManager.kt, source-local/src/commonMain/kotlin/tachiyomi/source/local/image/LocalCoverManager.kt
If the `cbz` archive of a local manga is encrypted then the cover will be generated inside an encrypted `cbi` archive and coil can read encrypted `cbi` archives now.
I also changed the default value of `encryptDatabase` from using an encrypted database if there is no unencrypted database yet to not using an encrypted database by default. I don't really know how changing the default value of a shared preference will effect the app after an update so feedback on this point would be appreciated.
=> Implemented local cover encryption

app/src/main/java/eu/kanade/tachiyomi/data/download/Downloader.kt
I changed the `archiveChapter` function to only use zip4j for encrypted downloads, because the zip4j implementation does not seem to work for some users in the Discord.
=> use zip4j only for encrypted downloads

app/src/main/java/eu/kanade/presentation/more/settings/screen/SettingsReaderScreen.kt, app/src/main/java/eu/kanade/tachiyomi/data/download/Downloader.kt, app/src/main/java/eu/kanade/tachiyomi/ui/reader/loader/RarPageLoader.kt, app/src/main/java/eu/kanade/tachiyomi/ui/reader/loader/ZipPageLoader.kt, app/src/main/java/eu/kanade/tachiyomi/ui/reader/model/ReaderPage.kt, app/src/main/java/eu/kanade/tachiyomi/ui/reader/setting/ReaderPreferences.kt, app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/pager/PagerPageHolder.kt, app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/webtoon/WebtoonPageHolder.kt, core/src/main/java/tachiyomi/core/util/system/ImageUtil.kt, i18n/src/main/res/values/strings_sy.xml
Make `comic book archive` caching optional instead of rolling it back completely. 
This fixes the issues users are having with opening `cbz` archives when their devices don't support zip4j's implementation correctly, but adds a new `comic book archive` caching preference instead of rolling the caching feature back completely like main Tachiyomi did.
I think this is a good Idea for multiple reasons 
- The bug that caching archives to disk aimed to fix is still around and this gives these users the option to use `cbz` archives if their devices support the zip4j implementation
- There are performance gains to be had by removing the overhead of unzipping pages on the fly especially if these pages are AES encrypted. AES encryption can make reading in webtoon mode a bit laggy and having another …
=> Make comic book archive caching optional instead of rolling it back completely 

app/src/main/java/eu/kanade/tachiyomi/data/coil/TachiyomiImageDecoder.kt
The old fix b3ab889 breaks encrypted thumbnails.
Buffered streams are not supported by zip4j. That's why it is necessary to open a fresh input stream before calling `CbzCrypto.detectCoverImageArchive`
I tested the fix with both avif and encrypted thumbnails
=> Fixed avif/encrypted thumbnails not loading

app/src/main/java/eu/kanade/presentation/reader/ChapterListDialog.kt
make it shorter like before
<table>
<tr>
<td>Before
<td>After
<tr>
<td> <img src="https://github.com/jobobby04/TachiyomiSY/assets/16263232/ba674aeb-961e-4ecd-860a-1e4da02c85d0">
<td> <img src="https://github.com/jobobby04/TachiyomiSY/assets/16263232/74406e5d-58f9-4a85-a60a-9d4677c03b1a">
</table>
=> Shorter Chapter List in Reader

app/src/main/java/eu/kanade/tachiyomi/ui/manga/MangaScreen.kt
Disable Mangadex recommendation if the delegated setting is disabled
=> Fix Mangadex recommendation

app/src/main/java/eu/kanade/presentation/more/settings/screen/SettingsLibraryScreen.kt, app/src/main/java/eu/kanade/tachiyomi/data/library/LibraryUpdateJob.kt, domain/src/main/java/tachiyomi/domain/library/service/LibraryPreferences.kt, i18n/src/commonMain/resources/MR/base/strings.xml
useful for source like mdex with multiple scanlator
https: //github.com/tachiyomiorg/tachiyomi/pull/9662
=> add toggle to auto mark read dupe chapter

app/src/main/java/eu/kanade/domain/ui/UiPreferences.kt, app/src/main/java/eu/kanade/presentation/more/settings/screen/SettingsBrowseScreen.kt, app/src/main/java/eu/kanade/tachiyomi/ui/browse/BrowseTab.kt, i18n-sy/src/commonMain/resources/MR/base/strings.xml
toggle to hide feed tab in Browse
<table>
<tr>
<th>toggle off
<th>toggle on
<tr>
<td><img src="https://media.discordapp.net/attachments/825346400953827349/1201344423523516486/image.png?ex=65c97a2e&is=65b7052e&hm=a4c2ebb5515e9219b5e4b0b25e7c58c5f5ab3b86d6300d77c4d9fc0662644f7a&=&quality=lossless">
<td><img src="https://media.discordapp.net/attachments/825346400953827349/1201344423838101514/image.png?ex=65c97a2e&is=65b7052e&hm=5fea8d8d067febc8761124c11e22e7ffc68702f6d9aa61b9372f51ee30b8ca19&=&quality=lossless">
</table>
=> Add Hide Feed tab toggle

app/src/main/java/eu/kanade/presentation/more/settings/screen/SettingsReaderScreen.kt, app/src/main/java/eu/kanade/tachiyomi/ui/reader/ReaderViewModel.kt, app/src/main/java/eu/kanade/tachiyomi/ui/reader/setting/ReaderPreferences.kt, i18n/src/commonMain/resources/MR/base/strings.xml
=> add mark read dupes on reading

app/src/main/java/eu/kanade/tachiyomi/data/download/Downloader.kt, app/src/main/java/eu/kanade/tachiyomi/ui/reader/loader/ZipPageLoader.kt, core/common/src/main/kotlin/eu/kanade/tachiyomi/util/storage/CbzCrypto.kt, source-local/src/androidMain/kotlin/tachiyomi/source/local/LocalSource.kt, source-local/src/androidMain/kotlin/tachiyomi/source/local/image/LocalCoverManager.kt
fixes #1076
Trying to access the image files directly causes access denied errors, switching to streams fixes this.
=> fix password protect downloads and copying ComicInfo files in LocalSource

app/src/main/java/eu/kanade/domain/sync/SyncPreferences.kt, app/src/main/java/eu/kanade/tachiyomi/data/library/LibraryUpdateJob.kt, app/src/main/java/eu/kanade/tachiyomi/data/sync/models/SyncTriggerOptions.kt, i18n/src/commonMain/resources/MR/base/strings.xml
So I removed the trigger for library update from the options, instead if sync is enabled it should always sync first before updating library.
Manga chapter is reshuffled like below:
(a simple refresh on the manga should fix it usually)
A little bit context:
Also syncing before library update should help with sources not being hit too much, since if main device for example have the latest data it should just send that instead of each devices trying to get the latest data from the sources, instead of 3 devices doing global update, it should be 1 device and the rest of them get the data from that device.
=> fix: sync on library update trigger.

app/src/main/java/eu/kanade/presentation/manga/components/MangaBottomActionMenu.kt, app/src/main/java/eu/kanade/tachiyomi/ui/library/LibraryScreenModel.kt, app/src/main/java/eu/kanade/tachiyomi/ui/library/LibraryTab.kt, app/src/main/java/eu/kanade/tachiyomi/ui/manga/EditMangaDialog.kt, app/src/main/res/layout/edit_manga_dialog.xml, i18n-sy/src/commonMain/resources/MR/base/strings.xml
- Add a button to the "Edit info" modal to be able to reset custom manga info.
- Add a button in the bottom bar in the library to be able to reset custom manga info for multiple galleries.
| Before | After |
| ------ |  ----- |
| ![Screenshot_20240316_230526_result](https://github.com/jobobby04/TachiyomiSY/assets/25001812/121646d6-59de-4414-8194-cc35ea51ca33) | ![Screenshot_20240316_230535_result](https://github.com/jobobby04/TachiyomiSY/assets/25001812/c48b60b9-8ab5-4783-a228-344ce3f710d2) |
=> Add option to reset custom manga info

app/src/main/java/exh/util/LewdMangaChecker.kt
PR for #1035 
- Added the `mature` tag
- Added `doujins` (doujins.com) and `luscious` (luscious.net) as filter keywords
=> Update LewdMangaChecker.kt to also filter the mature tag

app/src/main/java/eu/kanade/tachiyomi/ui/browse/migration/advanced/design/MigrationBottomSheetDialog.kt, app/src/main/java/eu/kanade/tachiyomi/ui/browse/migration/advanced/process/MigrationListScreenModel.kt, app/src/main/res/layout/migration_bottom_sheet.xml, domain/src/main/java/tachiyomi/domain/UnsortedPreferences.kt, i18n-sy/src/commonMain/moko-resources/base/strings.xml
This PR adds an option to the migration feature that will only show entries if newer chapters in other sources are available (by comparing the latest chapter number). This makes it easier to find more up-to-date sources. 
| Image 1 |
| ------- | 
| ![Screenshot_20240727_185836_TachiyomiSY](https://github.com/user-attachments/assets/b1f09d01-74e8-4e87-8530-7d4c05c7df0e) |
=> feat(migration): add option to only show entries with new chapters

app/src/main/java/eu/kanade/presentation/more/settings/screen/SettingsDataScreen.kt, app/src/main/java/eu/kanade/presentation/more/settings/screen/data/SyncSettingsSelector.kt
Previously you needed to click `Sync Now` to change what you would like to be synced which was unintuitive.  This PR moves `Chose what to sync` to it's own setting.
| Previous | Changed |
| ![image](https://github.com/user-attachments/assets/f43fa5f2-218e-4777-8c28-0765367d4c9f) | ![image](https://github.com/user-attachments/assets/ea6c066f-27a5-46e7-a8f2-684ee0b892e1) |
| Sync now: ![image](https://github.com/user-attachments/assets/26e9b39e-02c2-4c36-ad27-43255cb0c2f7) | Choose what to sync: ![image](https://github.com/user-attachments/assets/9d27385f-d597-44bc-83e0-ad3cd6456661) |
=> Move "Choose what to sync" out of "Sync now"

app/src/main/java/eu/kanade/presentation/reader/ChapterListDialog.kt
Issues with my implementation:
- The download state and progress don't update until chapter is scrolled out of the screen and back or the chapter list dialogue is closed and re-opened.
- The button itself still does nothing.
Closes  #1207
(I am unsure whether #497 is mentioning this or something else and why Syer mentioned that it's intentional.)
=> Show download state and progress on reader chapter list.

app/src/main/java/eu/kanade/tachiyomi/ui/manga/EditMangaDialog.kt, i18n-sy/src/commonMain/moko-resources/base/strings.xml
=> Allow adding multiple tags separated by commas

app/src/main/java/eu/kanade/presentation/library/components/LibraryToolbar.kt, app/src/main/java/eu/kanade/tachiyomi/ui/library/LibraryScreenModel.kt, app/src/main/java/eu/kanade/tachiyomi/ui/library/LibraryTab.kt
Tried to implement this draft pull (https://github.com/jobobby04/TachiyomiSY/pull/1203) as it was inactive for a long time.
- Add isSyncEnabled parameter to LibraryToolbar and LibraryRegularToolbar
- Pass isSyncEnabled from LibraryTab to LibraryToolbar
- Conditionally display sync library action based on isSyncEnabled
- Update LibraryContent to include isSyncEnabled parameter
- Adjust LibraryTab to handle sync-related functionality
- Remove direct dependency on SyncPreferences in LibraryToolbar
| Sync On | Sync Off |
| ![Screenshot_20240912-232212](https://github.com/user-attachments/assets/b23ebfab-2e1f-4585-8615-5cb010c4aebb) | ![Screenshot_20240912-232135](https://github.com/user-attachments/assets/d189e747-5c63-4f30-a74a-803e2d599a5a) |
=> Hide sync library option when sync is disabled

source-api/src/commonMain/kotlin/exh/metadata/metadata/NHentaiSearchMetadata.kt
Previews for newer doujins were not displayed because the images are mostly presented in .webp format, I suppose this little change can fix that issue.
Closes #1321
=> Add support for .webp image extension

app/src/main/java/eu/kanade/tachiyomi/data/track/BaseTracker.kt, app/src/main/java/eu/kanade/tachiyomi/data/track/Tracker.kt, app/src/main/java/eu/kanade/tachiyomi/data/track/anilist/Anilist.kt, app/src/main/java/eu/kanade/tachiyomi/data/track/anilist/AnilistApi.kt, app/src/main/java/eu/kanade/tachiyomi/data/track/anilist/dto/ALMangaMetadata.kt, app/src/main/java/eu/kanade/tachiyomi/data/track/bangumi/Bangumi.kt, app/src/main/java/eu/kanade/tachiyomi/data/track/bangumi/BangumiApi.kt, app/src/main/java/eu/kanade/tachiyomi/data/track/bangumi/dto/BGMSubject.kt, app/src/main/java/eu/kanade/tachiyomi/data/track/kitsu/Kitsu.kt, app/src/main/java/eu/kanade/tachiyomi/data/track/kitsu/KitsuApi.kt, app/src/main/java/eu/kanade/tachiyomi/data/track/kitsu/dto/KitsuMangaMetadata.kt, app/src/main/java/eu/kanade/tachiyomi/data/track/mangaupdates/MangaUpdates.kt, app/src/main/java/eu/kanade/tachiyomi/data/track/mangaupdates/MangaUpdatesApi.kt, app/src/main/java/eu/kanade/tachiyomi/data/track/mangaupdates/dto/Author.kt, app/src/main/java/eu/kanade/tachiyomi/data/track/mangaupdates/dto/MURecord.kt, app/src/main/java/eu/kanade/tachiyomi/data/track/mdlist/MdList.kt, app/src/main/java/eu/kanade/tachiyomi/data/track/model/TrackMangaMetadata.kt, app/src/main/java/eu/kanade/tachiyomi/data/track/myanimelist/MyAnimeList.kt, app/src/main/java/eu/kanade/tachiyomi/data/track/myanimelist/MyAnimeListApi.kt, app/src/main/java/eu/kanade/tachiyomi/data/track/myanimelist/dto/MALManga.kt, app/src/main/java/eu/kanade/tachiyomi/data/track/shikimori/Shikimori.kt, app/src/main/java/eu/kanade/tachiyomi/data/track/shikimori/ShikimoriApi.kt, app/src/main/java/eu/kanade/tachiyomi/data/track/shikimori/dto/SMMetadata.kt, app/src/main/java/eu/kanade/tachiyomi/source/online/all/MangaDex.kt, app/src/main/java/eu/kanade/tachiyomi/ui/manga/EditMangaDialog.kt, app/src/main/java/eu/kanade/test/DummyTracker.kt, app/src/main/java/exh/md/handlers/MangaHandler.kt, app/src/main/res/layout/edit_manga_dialog.xml, i18n-sy/src/commonMain/moko-resources/base/strings.xml
Allows setting manga info to the one provided by tracker (currently includes title, author, artist, thumbnail url and description).
Closes #1205 
TODO:
=> Get manga info from tracker

.github/ISSUE_TEMPLATE/report_issue.yml
Missing one forward slash in the https URI scheme for troubleshooting link
=> Fix broken URI scheme for troubleshooting link

app/src/main/java/eu/kanade/tachiyomi/data/backup/restore/restorers/MangaRestorer.kt, app/src/main/java/eu/kanade/tachiyomi/data/sync/service/SyncService.kt
**Fixes #1339**
If chapters are pushed to a sync service from Device A and these new chapters are then received by Device B, the source order of these chapters will be wrong because the existing chapters have not gotten their source order adjusted. This source order usually changes when new chapters get added or old ones get removed, however, as-is local chapters will still be in the order of before with the new chapters now colliding with the old chapters (leading to orders like "Chapter 38" -> "Chapter 43" -> "Chapter 37" -> "Chapter 42" -> ...).
The proposed changes now ensure that this corner case for syncing is caught and the `sourceOrder` of the chapters are now in the correct order. I made it so that existing behavior not sync-related should remain unaffected.
=> Maintain correct source order even when receiving new chapters from a sync service

app/src/main/java/eu/kanade/presentation/browse/BrowseTabWrapper.kt, app/src/main/java/eu/kanade/tachiyomi/ui/browse/migration/sources/MigrationSourcesScreen.kt, app/src/main/java/eu/kanade/tachiyomi/ui/browse/source/SourcesScreen.kt, app/src/main/java/eu/kanade/tachiyomi/ui/browse/source/SourcesTab.kt
Shows the global search action button in the top-right corner when using the SmartSearch source selection.
That helps users to select a source if they are unsure what to pick, for example when tapping on tracker recommendations.
Also adds a back button to the screen (might fix #865, not sure).
Closes #210
Closes #446
| Image 1 | 
| ------- | 
| <img src="https://github.com/user-attachments/assets/c779363c-a54e-4292-bee8-6b5641331039" width="300"> |
=> feat: add global search shortcut to SmartSearch

app/src/main/java/eu/kanade/tachiyomi/data/sync/SyncNotifier.kt
Categorize sync complete/error notifications as `CHANNEL_BACKUP_RESTORE_COMPLETE` instead of `CHANNEL_BACKUP_RESTORE_PROGRESS`. This matches the behavior of the BackupNotifier.
This doesn't completely fix  #1325, but it's a low-hanging fruit to improve the experience somewhat.
=> Use COMPLETE category when sync finishes

app/src/main/java/eu/kanade/domain/track/service/TrackPreferences.kt, app/src/main/java/eu/kanade/presentation/more/settings/screen/SettingsTrackingScreen.kt, app/src/main/java/eu/kanade/tachiyomi/data/track/BaseTracker.kt, app/src/main/java/eu/kanade/tachiyomi/data/track/Tracker.kt, app/src/main/java/eu/kanade/tachiyomi/data/track/anilist/Anilist.kt, app/src/main/java/eu/kanade/tachiyomi/data/track/anilist/AnilistApi.kt, app/src/main/java/eu/kanade/tachiyomi/data/track/anilist/dto/ALSearch.kt, app/src/main/java/eu/kanade/tachiyomi/data/track/mangaupdates/MangaUpdates.kt, app/src/main/java/eu/kanade/tachiyomi/data/track/mangaupdates/MangaUpdatesApi.kt, app/src/main/java/eu/kanade/tachiyomi/data/track/myanimelist/MyAnimeList.kt, app/src/main/java/eu/kanade/tachiyomi/ui/manga/track/TrackInfoDialog.kt, app/src/main/java/eu/kanade/test/DummyTracker.kt, i18n-sy/src/commonMain/moko-resources/base/strings.xml, source-api/src/commonMain/kotlin/exh/metadata/metadata/MangaDexSearchMetadata.kt, source-api/src/commonMain/kotlin/exh/metadata/metadata/base/TrackerIdMetadata.kt
Some sources like MD often have direct links/IDs to trackers, which can be used to automatically select the correct tracker entry. Implemented for MangaDex with MAL, AL, and MangaUpdates.
Also adds a new setting that disables this behavior.
https://github.com/user-attachments/assets/37698815-fd11-4415-9aec-324e6274e68b
=> feat(MangaDex): use tracker links to associate mangas automatically with trackers

app/build.gradle.kts, app/src/main/AndroidManifest.xml, app/src/main/java/eu/kanade/presentation/more/settings/screen/SettingsDataScreen.kt, app/src/main/java/eu/kanade/presentation/more/settings/widget/EditTextPreferenceWidget.kt, gradle/sy.versions.toml, i18n-sy/src/commonMain/moko-resources/base/strings.xml
This PR changes the sync API key preference from an `EditTextPreference` to a `CustomPreference` with a `EditTextPreferenceWidget`, which I modified to add an `IconButton`. The button launches a ActivityResultLauncher with a ScanContract, setting the API key when the intent result is returned.
| API key preference | QR scan activity |
| ![](https://github.com/user-attachments/assets/be8f57a0-bd27-41a6-ba84-d161276ffbc1) | ![image](https://github.com/user-attachments/assets/03ac4522-9fc9-4f33-9883-b806a42bc14c) |
Closes #1418
=> Add QR code scan button for sync API key

source-api/src/commonMain/kotlin/exh/metadata/metadata/EHentaiSearchMetadata.kt, source-api/src/commonMain/kotlin/exh/metadata/metadata/NHentaiSearchMetadata.kt
Fix the "Unknown author" field on the built-in and a delegated source:
- Set the Artist (🖌) field to joined Group tags (a.k.a. doujin circle) if available, joined Artist tags otherwise
- Set the Author (👤) field to joined Artist tags
- If Author and Artist have the same value, Artist (🖌) gets hidden
Null the description instead of writing `meta`
| Before | After |
| ![image](https://github.com/user-attachments/assets/ca5dce91-15ae-4628-bd6f-997beba9e7ab) | ![image](https://github.com/user-attachments/assets/1ddd05c6-d0ad-4aba-96b6-eeaa72f202a8) |
| ![image](https://github.com/user-attachments/assets/be01d19b-6da5-4990-956b-bc3936f50def) | ![image](https://github.com/user-attachments/assets/cd632946-f113-4560-8d03-00b58b54a8cf) |
=> Populate Author field and clear Description on a couple sources

app/src/main/java/exh/recs/batch/RecommendationSearchProgressDialog.kt
Closes #1431 
Added a check to keep screen on only while the recommendation search status is not idle.
Not sure why the progress dialog needs the screen to stay on. Should the entirety of this be removed?
=> Fix screen not turning off while in library tab

app/src/main/java/eu/kanade/presentation/more/settings/screen/SettingsReaderScreen.kt, app/src/main/java/eu/kanade/tachiyomi/ui/reader/setting/ReaderPreferences.kt, app/src/main/java/mihon/core/migration/migrations/Migrations.kt, app/src/main/java/mihon/core/migration/migrations/RemoveDuplicateReaderPreferenceMigration.kt
Removed  `markReadDupe` preference from `ReaderPreferences` as `markDuplicateReadChapterAsRead` from `LibraryPreferences` is the one that's actually used.
=> Remove the unused mark duplicate as read preference.

app/src/main/java/eu/kanade/tachiyomi/App.kt
Fixes issues with logging to file on certain devices (mine, for example).
This returns `<date>-<build_type>.log`.
https://github.com/jobobby04/TachiyomiSY/blob/ab5ff00c393991e2f239a347f7894dc42fc25342/app/src/main/java/exh/log/EnhancedFilePrinter.kt#L62
But, this creates `<date>-<build_type>.txt` causing issues. 
https://github.com/jobobby04/TachiyomiSY/blob/ab5ff00c393991e2f239a347f7894dc42fc25342/app/src/main/java/exh/log/EnhancedFilePrinter.kt#L76
This PR changes the extension to .txt to (hopefully) prevent any issues.
=> Change log file extension to .txt

app/src/main/java/eu/kanade/tachiyomi/source/online/all/EHentai.kt
Fixes #1445 
To match the date in the YYYY-MM-DD format, only the MATCH_SEEK_REGEX was modified.
=> Fix E-Hentai Jump/Seek match for detailed date
